### ISSUE TITLE
3D viewer error when opening

### ISSUE THREAD

**Issue by amirDahari1** [imagej/imagej2#280]
Hello and thank you for making this really useful tool,

I have an error when opening the 3D Viewer plugin, and I can't open any image. This is the message in the console:

```
[INFO] Reading available sites from https://imagej.net/

3D [dev] 1.6.0-scijava-2-pre11-daily-experimental daily

com.jogamp.opengl.GLException: Not a GL2 implementation
	at jogamp.opengl.es1.GLES1Impl.getGL2(GLES1Impl.java:4929)
	at org.scijava.java3d.JoglPipeline.createNewContext(JoglPipeline.java:6429)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:4602)
	at org.scijava.java3d.Canvas3D.createNewContext(Canvas3D.java:2376)
	at org.scijava.java3d.Renderer.doWork(Renderer.java:881)
	at org.scijava.java3d.J3dThread.run(J3dThread.java:271)
Exception occurred in RenderingErrorListener:
java.lang.RuntimeException
	at ij3d.ImageWindow3D$ErrorListener.errorOccurred(ImageWindow3D.java:351)
	at org.scijava.java3d.VirtualUniverse.notifyRenderingErrorListeners(VirtualUniverse.java:1198)
	at org.scijava.java3d.NotificationThread.processNotifications(NotificationThread.java:86)
	at org.scijava.java3d.NotificationThread.run(NotificationThread.java:104)
```

I am using Ubuntu 20.04
Graphics card Intel UHD 620

What can I do?  I am currently using the Volume Viewer plugin and it works fine but I need the 3D viewer plugin for the extra features.

Thanks!
Amir

**Comment by ctrueden** [comment]
@amirDahari1 Do you still see this error with a fresh download of Fiji-Latest from https://fiji.sc/ ?

**Comment by amirDahari1** [comment]
Hey @ctrueden, I can't recreate this issue because I don't have this volume anymore and I'm on a different operating system, my guess is that it's fixed now, thanks :)

**Comment by ctrueden** [comment]
@amirDahari1 Thank you for the reply! I'm going to close this for now. I know that JOGL still has issues on certain computers when the OpenGL libraries are not up to snuff, or when running in graphically-limited environments like inside a VM. For example, a common error on Windows VMs is `Java 3D ERROR : OpenGL 1.2 or better is required (GL_VERSION=1.1)` (fiji/3D_Viewer#18). In the case of Linux with `Not a GL2 implementation`, maybe installing [Mesa](https://en.wikipedia.org/wiki/Mesa_%28computer_graphics%29) would have helped? Sorry for the very belated and no-longer-helpful replies, but happy it's not vexing you anymore.
