### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Invalid service: net.imagej.legacy.LegacyService

### ISSUE THREAD

**Issue by workhours** [imagej/imagej2#301]
clone this repo to local directory by git-gui, configure project according to "https://imagej.net/develop/intellij". Run/Debug "ImageJ2" shows following exceptions:
<code>
Exception in thread "main" java.lang.IllegalArgumentException: Invalid service: net.imagej.legacy.LegacyService
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:278)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:285)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	... 9 more
Caused by: java.lang.RuntimeException: No _hooks field found in ij.IJ
It appears that this class was already defined in the class loader!
Please make sure that you initialize the LegacyService before using
any ImageJ 1.x class. You can do that by adding this static initializer:

	static {
		LegacyInjector.preinit();
	}

To debug this issue, start the JVM with the option:

	-javaagent:/C:/Users/XXX/.m2/repository/net/imagej/ij1-patcher/1.2.1/ij1-patcher-1.2.1.jar

To enforce pre-initialization, start the JVM with the option:

	-javaagent:/C:/Users/XXX/.m2/repository/net/imagej/ij1-patcher/1.2.1/ij1-patcher-1.2.1.jar=init

	at net.imagej.patcher.CodeHacker.javaAgentHint(CodeHacker.java:826)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:431)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:378)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	... 18 more
Caused by: java.lang.NoSuchFieldException: _hooks
	at java.base/java.lang.Class.getField(Class.java:2117)
	at net.imagej.patcher.LegacyInjector.alreadyPatched(LegacyInjector.java:422)
	... 21 more
</code>

Test environment:
OS: windows10
JDK: Oracle JDK 17.0.2
Intellj IDEA: 2021.3.1

**Comment by workhours** [comment]
debugging by step, it seems:
<code>
	findLoadedClass.setAccessible(true);
</code> 
thrown exception at `net.imagej.patcher.LegacyInjector` at line 405, don't know if this exception is expected

**Comment by Suikaba** [comment]
Did you build ImageJ2 with JDK bundled with it?
In my case, the error occurs when using `java 17 (SDK of 'imagej' module)` in Run/Debug Configurations.

**Comment by ctrueden** [comment]
The issue here is the use of Java 17 without the needed `--add-opens` arguments. We are switching the Fiji launcher to a new one we made called [Jaunch](https://github.com/apposed/jaunch), which passes the needed arguments specified by [the `fiji.toml` file](https://github.com/apposed/jaunch/blob/392c60e690fa19c4c12b9003696ad334fbad4dec/configs/fiji.toml).

Here is a list of the recommended arguments as of this writing:

```
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.desktop/sun.awt=ALL-UNNAMED
--add-opens=java.desktop/javax.swing=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED  # Linux only
--add-opens=java.desktop/com.apple.eawt=ALL-UNNAMED  # macOS only
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/java.time=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/sun.util.calendar=ALL-UNNAMED
--jdb|--add-opens=jdk.jdi/com.sun.tools.example.debug.tty=ALL-UNNAMED
```

The longer-term plan is to move away from the runtime byte-code patching of imagej-legacy, so that this problem becomes moot.
